---
name: sentimentipos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pytask
  - matplotlib
  - statsmodels
  - pysentiment2
  - numpy
  - pip:
      - kaleido==0.2.1
      - sentimentipos
