---
name: sentimentipos
channels:
  - conda-forge
  - nodefaults

dependencies:
  - conda-lock
  - json
  - ipykernel
  - jupyterlab
  - matplotlib
  - os
  - random
  - pandas
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.11
  - pysentiment2
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml
  - zipfile
  - pip:
      - -e .
      - kaleido
