---
name: sentimentipos
channels:
  - conda-forge
  # - nodefaults  # Remove this line

dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - openpyxl
  - pandas=1.5.3
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.11
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml
  - matplotlib
  - statsmodels
  - pysentiment2
  - pip:
      - -e .
      - kaleido
